container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
##    - aria2c --seed-time=1 --seed-ratio=1.0 "https://onejav.com/torrent/aukg481/download/400730/onejav.com_aukg481.torrent"
    - "aria2c https://www.dropbox.com/s/dl/957z0veaqvwfdbc/Boneka-Berhantu.mp4"
    - ffmpeg -i "Boneka-Berhantu.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Siboen Misteri Boneka Berhantu" -preset veryfast -s 960x540 Boneka-Berhantu-x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Boneka-Berhantu-x265.mp4"
